### PR TITLE
update AWS GoSDK to v1.12.46

### PR DESCRIPTION
**Pull request by codenrhoden**
This patch updates the AWS GoSDK from 1.10.38 to 1.12.46.

This is hopes of resolving #1118, where EBS volumes in a CN region are not working correctly.

This is currently untested, as I have not tried spinning up volumes in a CN region, and I still need to check that existing functionality is restored.

### CODE REVIEW

**Comment by akutz** [comment]
Hi @codenrhoden,

Why did you update the GoCSI info in `Gopkg.toml` instead of just using `dep ensure -update` to update AWS directly?

**Comment by codenrhoden** [comment]
LOL, I meant to explain that... Totally forgot.

So, if I ran `dep ensure -update`, with the AWS library, I got all kinds of resolver errors. Tried a bunch of trial and error, and flat out could not get it to work until I locked down both GoCSI and csi-vfs. Maybe I should have tried to look for an updated version of `dep` first, but it's been working so well lately...

**Comment by akutz** [comment]
Hi @codenrhoden,

I'm curious what resolver errors you received. Hmm.

**Comment by akutz** [comment]
Hi @codenrhoden,

Something like this?

```shell
$ dep ensure -update github.com/aws/aws-sdk-go
Solving failure: No versions of github.com/thecodeteam/gocsi met constraints:
	master: Could not introduce github.com/thecodeteam/gocsi@master, as its subpackage github.com/thecodeteam/gocsi/csp is missing. (Package is required by github.com/thecodeteam/csi-vfs@master.)
	v0.2.4: Could not introduce github.com/thecodeteam/gocsi@v0.2.4 due to multiple problematic subpackages:
	Subpackage github.com/thecodeteam/gocsi/csi is missing. Package is required by:
		(root)
		github.com/thecodeteam/csi-blockdevices@master	Subpackage github.com/thecodeteam/gocsi/mount is missing. Package is required by:
		(root)
		github.com/thecodeteam/csi-blockdevices@master
	v0.2.3: Could not introduce github.com/thecodeteam/gocsi@v0.2.3, as it is not allowed by constraints from the following projects:
	master from (root)
	master from github.com/thecodeteam/csi-vfs@master
	master from github.com/thecodeteam/csi-blockdevices@master

	v0.2.2: Could not introduce github.com/thecodeteam/gocsi@v0.2.2, as it is not allowed by constraints from the following projects:
	master from (root)
	master from github.com/thecodeteam/csi-vfs@master
	master from github.com/thecodeteam/csi-blockdevices@master

	v0.2.1: Could not introduce github.com/thecodeteam/gocsi@v0.2.1, as it is not allowed by constraints from the following projects:
	master from (root)
	master from github.com/thecodeteam/csi-vfs@master
	master from github.com/thecodeteam/csi-blockdevices@master

	v0.2.0: Could not introduce github.com/thecodeteam/gocsi@v0.2.0, as it is not allowed by constraints from the following projects:
	master from (root)
	master from github.com/thecodeteam/csi-vfs@master
	master from github.com/thecodeteam/csi-blockdevices@master

	v0.1.0: Could not introduce github.com/thecodeteam/gocsi@v0.1.0, as it is not allowed by constraints from the following projects:
	master from (root)
	master from github.com/thecodeteam/csi-vfs@master
	master from github.com/thecodeteam/csi-blockdevices@master

	master: Could not introduce github.com/thecodeteam/gocsi@master due to multiple problematic subpackages:
	Subpackage github.com/thecodeteam/gocsi/csi is missing. Package is required by:
		(root)
		github.com/thecodeteam/csi-blockdevices@master	Subpackage github.com/thecodeteam/gocsi/mount is missing. Package is required by:
		(root)
		github.com/thecodeteam/csi-blockdevices@master
```

**Comment by akutz** [comment]
Hi @codenrhoden,

So, you did the right thing. What occurred is that `dep` tries to build the object graph for the project's dependencies. The **entire** graph. Even if it's just to update a single, versioned dependency. This is necessary to ensure that the updated version doesn't introduce a conflict to the existing graph. However, due to the **existing** constraints around GoCSI the graph cannot be produced. 

So yeah, you did the right thing.

**Comment by codenrhoden** [comment]
Took this for a spin on AWS today. no regressions found (wasn't expecting any, the go library is pretty stable), as I was able to do the normal create/attach/detach/remove cycle just fine.

I *tried* to use the `cn-north-1` region, but got messages that EC2 is not available in that region. Not sure what it takes to get access to it. Once CI completes, I plan to merge this. Then I'll ping @spatialvlad and see if he able to take the `unstable` build for a spin to see if it resolves his issue. He indicated that it might not, as the AWS GoSDK we were using should have already supported the region... But, updating it is worth a shot.

**Pull request merged**
